### ISSUE TITLE
Footer Links

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm.github.io#10]
The footer is a little bit useless at the moment. I think either we just make the links actually go places, or—hear me out—we choose better stuff to put there. I don't know what, yet, of course, but surely we can think of something. Perhaps contact info? Anyway, this 'issue' is really about making the footer more than a bunch of dead links.

**Comment by radiolevity** [comment]
Footer updated to be less ugly (but still contains useless links)

**Comment by gugek** [comment]
So at this point keep the footer minimal like you have. *for now keep what you have*

On chapelhillfriends.org: right now the footer links are more a quick link area for people who use the site regularly and know where they are going. 

![image](https://user-images.githubusercontent.com/223778/50318605-37d4b780-0490-11e9-86b6-a7bc819ddd29.png)

I think this is a good opportunity to completely reimagine the navigation and architecture. 

But going ahead we can think about the following: 

For an asset that is going to be reusable throught the site we can have three areas in the footer:

1. Navigation for internal audience. Probably to a separate quick links page.
2. Address, contacts, and social media
3. Schedule and link to calendar.

Lets keep this open for now but keep this as a tracker.

**Comment by radiolevity** [comment]
I cleaned up the footer. It's not perfect, but further changes will be a part of the Summer 2019 Content Revamp™ so I'm closing this for now.
