### ISSUE TITLE
Visit & Learn content decisions

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm.github.io#16]
A lot of the visit & learn sections have a lot of links to... random things. Each one will need to be evaluated for whether or not they should be included in the final page. Honestly I have no idea what stuff needs to be moved over and what doesn't.

**Comment by gugek** [comment]
Ministry and Worship will need to review and give ok on which links etc...

**Comment by radiolevity** [comment]
link notes addressed to the best of my ability. I think we can close this for now.
