### ISSUE TITLE
Building Use Calendar

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#26]
Separate building use calendar at: http://chapelhillfriends.org/bucalendar.html

**Comment by gugek** [comment]
Not sure if there is a way of setting it up in more of a modular manner rather than having a separate js function.

**Comment by radiolevity** [comment]
I think I'm going to get rid of Full Calendar. It looks nice but its functionality is somewhat lacking, and also it keeps failing unexpectedly. Also, bucalendar link added to footer

**Comment by gugek** [comment]
Ok get rid of full calendar. I'm going to go ahead and close #25 and update the footer links to reflect our current pages.

**Comment by radiolevity** [comment]
Okay, it's fixed, and still using Full Calendar. I'll close this for now because it has been working consistently for a while now.
