### ISSUE TITLE
Incorporate directions into landing page

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#27]
Bring in feature/info from http://chapelhillfriends.org/map.html into landing page.

Also add information about parking.

**Comment by radiolevity** [comment]
Map added in modal; @gugek what parking info is necessary?

**Comment by gugek** [comment]
Looks like we had something else in an old Visit page: http://chapelhillfriends.org/visit.html

> Where do I park? Can I find my way around?
> There is some parking in front of our Meeting House. If our lot is full, there is always plenty of parking in the UNC lot next door (and the UNC lot is free on Sunday morning). Finding your way around is easy. A little before 11am on Sunday you will see people going in the front door of our Meeting House. Just come in and sit down. 

Can include that in the Visit/Learn section as another accordion section I think and then a link off the main page. Or include it in the actual modal.

I'm open to any creative solution.

**Comment by gugek** [comment]
Seems like https://chfm.github.io/visit-and-learn.html includes something in the *Where is* section. But if you can incorporate something closer to the landing page that would be good.

**Comment by radiolevity** [comment]
okay that's fixed, "where should I park" and "how will I find my way around" added to visit and learn

**Comment by gugek** [comment]
a26c741 Done!
