### ISSUE TITLE
Inconsistent permalinking

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm.github.io#29]
Should the permalinks end in ".html"? I feel like they shouldn't, but even if they do, they all should consistent. This is admittedly not all that important.

**Comment by gugek** [comment]
If there is a corresponding page on chapelhillfriends.org it should have the same URL as it did before. The trick becomes if we redo the architecture we can have sub-directory/index pages which lead as portals or groupings for related content.

**Comment by gugek** [comment]
refactored also and moved files into `/content/` directory.

**Comment by gugek** [comment]
Closed in d3f1283
