### ISSUE TITLE
Dynamic First Day Schedule

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#33]
Business meeting weeks versus regular weeks. Maybe base on data file.

**Comment by radiolevity** [comment]
I can't tell an easy way to do this, so I just added "/ business meeting" to the home page and will leave this open until it can be solved. If we want it to be truly dynamic then we need to either rebuild the page every week or else use jQuery, neither of which are great solutions.

**Comment by gugek** [comment]
Problem is that business meeting is at 9a. Lets go back to the original 9:45a forum and update the text to reflect when business meeting is held.

**Comment by gugek** [comment]
rolled back in 07788a3
