### ISSUE TITLE
Navbar wrapping

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm.github.io#39]
With the inclusion of "Our Community" in the navbar there are now clipping problems at certain medium-ish page sizes. There are several possible solutions, including 1) having a hamburger menu at larger sizes, 2) changing the link signatures to be shorter, or 3) switching to a different nav configuration (perhaps on the left).

**Comment by gugek** [comment]
1. Can it respond at 840px? Or is it out of the box set to something else which causes issues by overriding?
2. We can probably drop contact down to the footer (getting crowded there) & change Donate to Give.
3. lets keep the nav config the same (except for 1 or 2)

A new option (4) is to fold chfm.html and contact.html into a single page -> about.html and deprecate that, but I don't really have time to figure out the stakeholders on those pages.

I'd prefer to do (1). 

Also centering the nav elements in the bar would be a nice piece of polish.

**Comment by radiolevity** [comment]
Oh, I, uh, I already fixed it. @gugek if you don't like this solution I'd be happy to try something less radical. I'm not totally convinced by this method, but it seems to work reasonably well.

**Comment by gugek** [comment]
The sidebar is good. It works better for me after getting over losing the header navigation.

Some polish:

- Add tooltips for desktop (and whatever is equivalent in mobile) to indicate link's text or function
- We can rethink what goes in the top level nav versus footer nav. I have an internal vs. external audience categorization in mind: of course this is something that we would have to revisit since we're trying to get to a 1:1 migration point;  instead of revisiting the whole information architecture.

**Comment by radiolevity** [comment]
I agree with the second point, we'll table it for now but it can be part of my "Summer Website Content Revamp Jamboree" I have planned (which I suppose will probably involve a lot of committee consultations).

In the mean time, is the hamburger/expand functionality not enough for tooltips? I can add them as well but I feel like it would detract from the simplicity of the nav design.

**Comment by gugek** [comment]
My feeling is that the bar doesn't have enough to indicate what each function (icon) goes to. If it was just the hamburger that is a pretty typical navigation treatment, but with all the icons there it gets a bit more confusing, and its really not clear what the function is of each.

So first interaction opens the container: hover, touch or click (treat the whole column as the hamburger). This slides out the container and then you can click where you want to go.

Thinking about it more we probably go with a few (3ish) items in the header. They can collapse down to icons when you respond to a narrower screen. Then keep the idea of having the side nav for all the rest of the top level. This means we get 3 levels of navigation.

1. Header items: Visit and learn, Contact, Calendar
2. Sidenav: rest of the stuff with along with the header navigation items
3. Footer items: and our second level

**Comment by radiolevity** [comment]
Okay, I'll try to implement a more standard type navbar. I think you're right, and on mobile it gets annoyingly in the way. The new one will collapse down all the way. We can potentially also include some sort of tiers or nesting but let's see how this works, first.

**Comment by radiolevity** [comment]
Okay, new navbar implemented

**Comment by gugek** [comment]
![6EF9B9C6-69A0-46AC-B96C-D9EE387AF33B](https://user-images.githubusercontent.com/223778/55600321-7c2b5100-5729-11e9-98e0-1b60e18d1e4d.jpeg)

Let’s try to have a fixed header again. Use the container button on the left. Put three items in another div on the header that is responsive but on the right. Maybe another control on the right for feedback and other nav.

**Comment by radiolevity** [comment]
Okay, I kind of did your idea. My only complaint with what I wrote is that the "click outside to dismiss" menu functionality is broken on mobile Safari—I added a close button but a better solution may be in order at a later date. I think this can still be closed, though, with your approval @gugek

**Comment by gugek** [comment]
Looks good. I actually was wondering if the header bar in the upper right can include some links that respond down according to screen size. The three there are actually ok I think, but pretty intuitive as to what their functionality is. But I'd like to surface some of the major destinations:

- visit and learn
- our community
- contact

<img width="497" alt="Screen Shot 2019-04-10 at 07 32 29" src="https://user-images.githubusercontent.com/223778/55875576-5eb01a00-5b63-11e9-87b2-8451ce7da854.png">

Search can go back to the left container I think, and the feedback button should be temporary or can go back to the main side nav.

**Comment by gugek** [comment]
Spacing of the bar on some browsers is a bit weird with scroll bars

![image](https://user-images.githubusercontent.com/223778/55890711-2f100a80-5b81-11e9-8f07-d9460b81ec2c.png)

**Comment by radiolevity** [comment]
Okay, both problems fixed! I think this version works well and I like its simplicity.

**Comment by gugek** [comment]
ok'd looks good lets freeze the navbar stuff until we can get more input and do more design.
