### ISSUE TITLE
Custom Google Search feature

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#49]
- Modal doesn't scroll well in some mobile views.
- Lots of advertisements. Only removable if we are on Google for Nonprofits. 
- Look into other options: Bing?

**Comment by radiolevity** [comment]
I think this might work: https://github.com/jekylltools/jekyll-tipue-search

**Comment by radiolevity** [comment]
Okay so I switched google for tipue. That said, I think it would be worth trying to get google for nonprofits set up because tipue's indexing is kind of terrible. But it doesn't have ads and it runs on gh pages so it will work for now.

**Comment by gugek** [comment]
this is fine: closed in 51abe2f16859e91976e31fd98dd79a2606e334bf
