### ISSUE TITLE
Inconsistent links

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm.github.io#5]
Ideally, all the links would be the page name off of the domain (e.g. chapelhillfriends.org/calendar). Right now they have a middle step (e.g. chapelhillfriends.org/chfm-website/calendar) that requires hard-coding in the about section. I think figuring out how to make the links fit the above style might be advisable.

**Comment by gugek** [comment]
use the `base-url` parameter in the config.yml.  When you deploy to a different host or path you change that parameter; to handle multiple destinations you can setup another branch and switch back and forth.

**Comment by gugek** [comment]
fixed in #23
