### ISSUE TITLE
/popups/glossary.html

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#52]
- Redirect to a glossary.html that is built off of the visit and learn data for the what do Quakers mean when they say. (Google seems to have a bit of traffic to this page).
- Alternatively have a direct link that https://www.chapelhillfriends.org/visit-and-learn.html#heading-what-do-quakers-mean-when-they-say that card is opened?

**Comment by radiolevity** [comment]
I will add a `glossary.html` in a little while, which has the benefit of removing the “What do Quakers mean when they say” from the Visit and Learn page (since it does not work very well in that format)

**Comment by radiolevity** [comment]
Okay `/glossary.html` is now its own page. I can potentially make it a popover if that would be helpful, although I don't know if that would really add a lot to the functionality.

**Comment by gugek** [comment]
Closed in #6c24826
