### ISSUE TITLE
Zoom Pages

### ISSUE THREAD

**Issue by gugek** [chfm/chfm.github.io#63]
Via @buborc:

> There are 2 links that are supposed to go to "gallery_view.html", but neither one seems to work. My first attempt at fixing the link that is going to "GalleryView_inApp.htm" instead of to  "gallery_view.html" failed. Maybe a trivial error on my part or maybe not but I'm out of time right now too.

**Comment by gugek** [comment]
Check to see if 7d9df2ee54a4855c45f5c2f3a74b2201f2d90d73 and b8cb3ba95b34049a8ebbc509a8bedbf73ca2761d fix the issues. 

I added responsive image classes to the `<img>` elements. Also checked the various links to `{{ site.baseurl }}/zoom/gallery_view.html`

**Comment by buborc** [comment]
what you did fixed it. Thanks!
