### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by finnjames** [chfm/chfm.github.io#8]
It exists but it's bad. Make it better, or at least make it have content. @gugek I'm assigning myself to this but I need your feedback on what it should look like!

**Comment by gugek** [comment]
So lets use the existing art, look for an email.

The features of the landing page should be inline with the home page. In fact we probably just need one of the two.

The landing page should have the following content:

1. header
2. call to action ... 5-10 words ... a good George Fox quote would be good. But that could be certianly something that Ministry & Worship can come up with. probably include the: *We joyfully embrace the full spectrum of the light within, made visible through the participation of people of all beliefs, cultures, backgrounds, abilities, ethnicities and races, sexual orientations, and gender identities.* statement
3. Currently section
4. About section: *The Chapel Hill Friends is an unprogramed meeting established in 1937. We are a member of the Piedmont Friends Yearly Meeting. Our Visit / Learn page has basic information about what to expect at a Quaker Meeting for Worship. If you have additional questions or would like to know more about Quakers, feel free to contact us.*
4. Location and directions information
5. footer

**Comment by radiolevity** [comment]
Okay, I think the landing page is in workable shape. Enough that on my next commit I will replace the home page with it. It has a darker theme than the rest of the site for a e s t h e t i c purposes, but otherwise it's essentially just the old home page plus a big photo.
